Rails(応用)課題6を回答しました.
Naokichi55/recommended_food_app pull request #2
Opened 2023-11-06 13:56 UTC by Naokichi55

# Rails(応用)課題6
 -Rails(応用)課題５にモデルの関連づけを行いました。課題６を提出します。

2023-11-07 03:30 UTC, T-Tsujii requested changes

2023-11-07 03:30 UTC, T-Tsujii commented on app/controllers/foods_controller.rb
> +    redirect__to root_path, alert: "権限がありません"
@Naokichi55 
フラッシュが入っていますが、現状ですとフラッシュは表示されないのではないでしょうか。

（タブを２つ開き、片方のタブで削除した food を、もう片方で更新すると、set_food のこのコードが動きます）

2023-11-10 09:00 UTC, Naokichi55 commented on app/controllers/foods_controller.rb
> +    redirect__to root_path, alert: "権限がありません"
@T-Tsujii 
ご指摘のようにフラッシュが表示されませんでした。find_byを使ったフラッシュ表示を試みましたが、うまくいかずエラー表示に変更しました。

2023-11-10 09:07 UTC, T-Tsujii approved these changes
ひとまずこちらでOKです！

`find_by` を使用してもフラッシュが出ないのは、フラッシュを表示するビューファイルが入っていなかったからだと思います。

2023-11-11 01:54 UTC, Naokichi55 commented
> ひとまずこちらでOKです！
> 
> `find_by` を使用してもフラッシュが出ないのは、フラッシュを表示するビューファイルが入っていなかったからだと思います。



> ひとまずこちらでOKです！
> 
> `find_by` を使用してもフラッシュが出ないのは、フラッシュを表示するビューファイルが入っていなかったからだと思います。

2023-11-11 01:54 UTC, closed without merging

2023-11-11 01:59 UTC, Naokichi55 commented
ご確認ありがとうございます。実は一度フラッシュファイルを追加して実施しました。その際find_byでエラーが出た事、修正しエラー解消されましたが今度は削除できない事象が発生しておりました。時間を見つけfind_byの使い方等もう少し勉強するつもりです。その際わからないことがあれば質問スレッドで質問するようにします。